name:                hant
version:             0.1.0.0
github:              "FM24-Hant/Hant"
license:             BSD3
author:              "anonymous"
maintainer:          "anonymous"
copyright:           "anonymous"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <>

dependencies:
- base >= 4.7 && < 5
- lens
- containers
- megaparsec
- parser-combinators
- bytestring
- xeno
- directory
- split
- filepath
- text
- universe-base
- sbv
- mtl
- random
- criterion
- async
- stm
- time

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -O2

default-extensions:
- ImportQualifiedPost
- ScopedTypeVariables
- OverloadedStrings
- TupleSections

library:
  source-dirs: src

executables:
  hant-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hant

tests:
  hant-test:
    main:                Main.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hant
    - sydtest
